dependencies:
  - ipython
  - numba=0.53.1
  - numpy=1.20.2
  - rdkit::rdkit
  - scikit-learn=0.24.1
  - matplotlib
  - dask=2021.04.0
  - dask-ml=1.8.0
  - jupyter
  - h5py=3.2.1
  - joblib=1.0.1
  - pandas=1.2.4
  - pip=21.0.1
  - pip:
    - loguru==0.5.3
    - gensim==3.8.3
    - setuptools==49.6.0
    - seaborn==0.11.1
    - palettable==3.3.0
    - click==7.1.2
    - umap-learn==0.5.1
    - networkx==2.5.1
    - git+https://github.com/laserkelvin/mol2vec.git@850d944d5f48a58e26ed0264332b5741f72555aa#egg=mol2vec
    - "-e ."
